export const REMOTION_CPU_EFFECTS = {
  transitions: [
    'fade',
    'wipe',
    'slide',
    'zoom',
    'film-burn',
    'blur-slide',
    'cross-zoom',
    'dreamy-zoom',
    'linear-blur',
    'push-cut',
  ] as const,
  looks: [
    'none',
    'grayscale',
    'sepia',
    'vintage',
    'cinematic',
    'blur',
    'glow',
    'high-contrast',
    'soft',
  ] as const,
  motion: [
    'none',
    'ken-burns',
    'pan',
    'rotate',
    'push-in',
    'pull-out',
    'float',
    'tilt-3d',
    'parallax-3d',
  ] as const,
  overlays: [
    'none',
    'vignette',
    'film-grain',
    'light-leak',
    'letterbox',
  ] as const,
  professionalEffects: [
    'chromatic-aberration',
    'color-correction',
    'glow',
    'pixelate',
    'zoom-blur',
    'vignette',
    'light-leak',
  ] as const,
  motionBlur: {
    supported: true,
    shutterAngle: { min: 0, max: 360, recommended: [90, 180] },
    samples: { min: 2, max: 8, recommended: [4, 5, 6] },
  },
  captions: {
    supported: true,
    styles: ['clean', 'cinematic', 'tiktok', 'karaoke'] as const,
    positions: ['top', 'center', 'bottom'] as const,
    fontSize: { min: 20, max: 120 },
    maxItemsPerRender: 300,
  },
  motionTitles: {
    supported: true,
    styles: ['clean', 'cinematic', 'neon', 'minimal'] as const,
    animations: ['fade-up', 'slide-left', 'slide-right', 'pop', 'zoom-in', 'word-rise', 'lower-third'] as const,
    positions: ['top', 'center', 'bottom'] as const,
    fontSize: { min: 24, max: 180 },
    maxItemsPerRender: 80,
  },
  clipMotion: {
    supported: true,
    presets: ['fade', 'slide-left', 'slide-right', 'slide-up', 'slide-down', 'zoom-in', 'zoom-out', 'bounce', 'elastic', 'spin', 'swing'] as const,
    intensity: { min: 0.25, max: 2 },
    duration: { min: 0.1, max: 10 },
  },
  proceduralMotion: {
    supported: true,
    presets: ['particles', 'orbit', 'pulse-grid', 'starfield'] as const,
    intensity: { min: 0, max: 1 },
    speed: { min: 0.1, max: 4 },
    controls: ['seed', 'color', 'accentColor'] as const,
    deterministic: true,
  },
  vectorAnimations: {
    supported: true,
    formats: ['lottie', 'rive'] as const,
    lottie: {
      remoteJson: true,
      controls: ['loop', 'playbackRate', 'direction'] as const,
    },
    rive: {
      remoteRiv: true,
      controls: ['fit', 'alignment', 'artboard', 'animation'] as const,
    },
    placement: ['start', 'end', 'x', 'y', 'scale', 'opacity'] as const,
    maxItemsPerRender: 40,
  },
  three: {
    supported: true,
    input: 'GLB',
    labels: 'M1, M2, ...',
    lighting: ['studio', 'soft', 'dramatic'] as const,
    controls: [
      'scale',
      'position x/y/z',
      'rotation x/y/z',
      'auto rotation',
      'rotation speed',
      'camera distance',
      'camera field of view',
      'GLB animation name',
      'background color',
    ] as const,
    maxScenesPerRender: 24,
  },
};

export const REMOTION_CPU_PUBLIC_CATALOG = {
  engine: 'Nayla Render CPU',
  purpose: 'Edición y composición profesional en Vercel Sandbox sin alquilar GPU.',
  transitions: REMOTION_CPU_EFFECTS.transitions,
  looks: REMOTION_CPU_EFFECTS.looks,
  motion: REMOTION_CPU_EFFECTS.motion,
  overlays: REMOTION_CPU_EFFECTS.overlays,
  professionalEffects: REMOTION_CPU_EFFECTS.professionalEffects,
  motionBlur: REMOTION_CPU_EFFECTS.motionBlur,
  captions: REMOTION_CPU_EFFECTS.captions,
  motionTitles: REMOTION_CPU_EFFECTS.motionTitles,
  clipMotion: REMOTION_CPU_EFFECTS.clipMotion,
  proceduralMotion: REMOTION_CPU_EFFECTS.proceduralMotion,
  vectorAnimations: REMOTION_CPU_EFFECTS.vectorAnimations,
  three: REMOTION_CPU_EFFECTS.three,
  controls: [
    'duración por clip',
    'volumen',
    'fade de audio/video',
    'velocidad',
    'recorte',
    'retraso',
    'escala',
    'brillo',
    'contraste',
    'saturación',
    'hasta 6 efectos profesionales encadenados por clip',
    'subtítulos sincronizados con estilos clean, cinematic, tiktok y karaoke',
    'títulos y lower thirds animados por frame con GSAP',
    'entradas y salidas GSAP deterministas para fotos y videos',
    'partículas, órbitas, rejillas pulsantes y campos de estrellas procedurales',
    'animaciones Lottie JSON y Rive .riv sincronizadas por frame',
    'escenas GLB 3D reales con cámara, luces, rotación y animación interna',
  ],
};
