export const REMOTION_CPU_EFFECTS = {
  transitions: [
    'fade',
    'wipe',
    'slide',
    'zoom',
    'film-burn',
    'blur-slide',
    'cross-zoom',
    'dreamy-zoom',
    'linear-blur',
    'push-cut',
  ] as const,
  looks: [
    'none',
    'grayscale',
    'sepia',
    'vintage',
    'cinematic',
    'blur',
    'glow',
    'high-contrast',
    'soft',
  ] as const,
  motion: [
    'none',
    'ken-burns',
    'pan',
    'rotate',
    'push-in',
    'pull-out',
    'float',
    'tilt-3d',
    'parallax-3d',
  ] as const,
  overlays: [
    'none',
    'vignette',
    'film-grain',
    'light-leak',
    'letterbox',
  ] as const,
  professionalEffects: [
    'chromatic-aberration',
    'color-correction',
    'glow',
    'pixelate',
    'zoom-blur',
    'vignette',
    'light-leak',
  ] as const,
  motionBlur: {
    supported: true,
    shutterAngle: { min: 0, max: 360, recommended: [90, 180] },
    samples: { min: 2, max: 8, recommended: [4, 5, 6] },
  },
  captions: {
    supported: true,
    styles: ['clean', 'cinematic', 'tiktok', 'karaoke'] as const,
    positions: ['top', 'center', 'bottom'] as const,
    fontSize: { min: 20, max: 120 },
    maxItemsPerRender: 300,
  },
  gsapMotion: {
    supported: true,
    presets: [
      'fade',
      'slide-left',
      'slide-right',
      'slide-up',
      'slide-down',
      'zoom-in',
      'zoom-out',
      'bounce',
      'elastic',
      'spin',
      'swing',
    ] as const,
    intensity: { min: 0.25, max: 2 },
    duration: { min: 0.1, max: 10 },
  },
};

export const REMOTION_CPU_PUBLIC_CATALOG = {
  engine: 'Nayla Render CPU',
  purpose: 'Edición y composición profesional en Vercel Sandbox sin alquilar GPU.',
  transitions: REMOTION_CPU_EFFECTS.transitions,
  looks: REMOTION_CPU_EFFECTS.looks,
  motion: REMOTION_CPU_EFFECTS.motion,
  overlays: REMOTION_CPU_EFFECTS.overlays,
  professionalEffects: REMOTION_CPU_EFFECTS.professionalEffects,
  motionBlur: REMOTION_CPU_EFFECTS.motionBlur,
  captions: REMOTION_CPU_EFFECTS.captions,
  gsapMotion: REMOTION_CPU_EFFECTS.gsapMotion,
  controls: [
    'duración por clip',
    'volumen',
    'fade de audio/video',
    'velocidad',
    'recorte',
    'retraso',
    'escala',
    'brillo',
    'contraste',
    'saturación',
    'hasta 6 efectos profesionales encadenados por clip',
    'subtítulos sincronizados con estilos clean, cinematic, tiktok y karaoke',
    'entradas y salidas GSAP deterministas por clip',
  ],
};
